name: Deploy Kovanica Node

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Spajanje na server i deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/kovanica-ledger
            git pull origin main
            cargo build --release
            pm2 restart ecosystem.config.js
